fixed_costs = float(input("Enter fixed costs: "))
price_per_unit = float(input("Enter price per unit: "))
cost_per_unit = float(input("Enter cost per unit: "))
break_even_point = fixed_costs / (price_per_unit - cost_per_unit)
print(f"Break-Even Point: {break_even_point:.2f} units")